spring:
    datasource:
        url: jdbc:mysql://localhost/wrkshp
        username: root
        password: MySQL@ROG
        driver-class-name: com.mysql.jdbc.Driver
        initialize: true
        separator: $$;
        type: org.apache.tomcat.jdbc.pool.DataSource
        tomcat:
            max-wait: 10000
            max-active: 50
            test-on-borrow: true
            validation-query: SELECT 1
    jpa:
        database: mysql
        generate-ddl: true
        show-sql: true