spring:
    datasource:
        url: jdbc:mysql://localhost:3306/wrkshpdev?useConfigs=maxPerformance&useSSL=false&characterEncoding=utf8
        username: root
        password: MySQL@ROG
        driver-class-name: com.mysql.jdbc.Driver
        initialize: false
#        separator: $$;
        type: org.apache.tomcat.jdbc.pool.DataSource
        tomcat:
            max-wait: 30000
            max-active: 100
            max-idle: 100
            test-on-borrow: true
            validation-query: SELECT 1
    jpa:
        database: mysql
        generate-ddl: true
        show-sql: true
    thymeleaf:
        cache: false

security:
    sessions-policy: IF_REQUIRED
    maximum-sessions: 10
    
web:
    default-page-size: 50